<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class News extends Model
{
    use HasFactory;
    protected $fillable = ['title', 'image', 'body'];
    protected static function boot()
    {
        News::deleting(function ($news){
            $image = str_replace(env('STORAGE_PATH'), '', $news->image);
            if (\Storage::disk('public')->exists($image)){
                \Storage::disk('public')->delete($image);
            }
        });
        parent::boot(); // TODO: Change the autogenerated stub
    }
}
