<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;
    protected $fillable = ['name', 'price', 'image', 'body', 'sale', 'category_id'];

    public function category(){
        return $this->belongsTo(Category::class);
    }
    protected static function boot()
    {
        Product::deleting(function ($product){
            $image = str_replace(env('STORAGE_PATH'), '', $product->image);
            if (\Storage::disk('public')->exists($image)){
                \Storage::disk('public')->delete($image);
            }
        });
        parent::boot(); // TODO: Change the autogenerated stub
    }
}
